#!/bin/sh
# Start composition manager to enable tranparency
xcompmgr &

# Use feh to set background
# feh creates ~/.fehbg when it is used to set the background
if [ -f $HOME/.fehbg ]; then
    $HOME/.fehbg
fi

# Background loop to update status bar
# Will use output of ~/.dwm_status script if present
while true; do
    if [ -f $HOME/.dwm_status ]; then
        xsetroot -name "$($HOME/.dwm_status)"
    else
        xsetroot -name "$(date +'%a %e %b %R')"
    fi
    sleep 2
done &

# Finally start the dynamic window manager
exec dwm

