#!/bin/sh
# Start composition manager to enable tranparency
xcompmgr &

# Use feh to set background
# feh creates ~/.fehbg when it is used to set the background
if [ -f $HOME/.fehbg ]; then
    $HOME/.fehbg
fi

# Replace notification-daemon with statnot
killall notification-daemon >/dev/null 2>&1
statnot &

# Finally start the dynamic window manager
while true; do
    dwm 2> ~/.dwm.log
done

